# Generated by Django 3.1.7 on 2023-07-03 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatdowant',
            name='what_do_want',
            field=models.CharField(choices=[('1', 'Check How Innovative my project is'), ('2', 'Check my answer against grant criteria')], default='1', max_length=200),
        ),
        migrations.CreateModel(
            name='BriefOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_overview', models.CharField(blank=True, max_length=500, null=True)),
                ('feature_1', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_2', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_3', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_4', models.CharField(blank=True, max_length=200, null=True)),
                ('feature_5', models.CharField(blank=True, max_length=200, null=True)),
                ('competitor_1', models.CharField(blank=True, max_length=200, null=True)),
                ('competitor_2', models.CharField(blank=True, max_length=200, null=True)),
                ('competitor_3', models.CharField(blank=True, max_length=200, null=True)),
                ('app_choice', models.CharField(choices=[('1', 'Mobile App'), ('2', 'Web App'), ('3', 'IOT')], default='1', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
