# Generated by Django 3.1.7 on 2023-07-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jbt', '0002_auto_20230703_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grantapplyfor',
            old_name='eic_accerlarator',
            new_name='grant_type',
        ),
        migrations.RemoveField(
            model_name='grantapplyfor',
            name='sbir',
        ),
        migrations.RemoveField(
            model_name='grantapplyfor',
            name='smart_innovate',
        ),
    ]
